name: DT-Engine-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - argon2-cffi
  - attrs
  - beautifulsoup4
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - decorator
  - defusedxml
  - ipykernel
  - jedi
  - jinja2
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab_server
  - nbconvert
  - nbformat
  - openssl
  - pandas
  - pip
  - prometheus_client
  - python-dateutil
  - pyyaml
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - wheel
  - zlib
  - pip:
      - ai21
      - ai21-tokenizer
      - aiohttp
      - aiosignal
      - async-lru
      - attrs
      - boto3
      - botocore
      - distributed
      - huggingface-hub
      - langchain
      - matplotlib
      - numpy
      - openai
      - pandas
      - scipy
      - seaborn
      - tqdm
      - typing-extensions
      - yarl
